import express from 'express';
import Hello from './hello.js';
import Lab5 from './Lab5.js';
import CourseRoutes from './courses/routes.js';
import cors from "cors";
import mongoose from "mongoose";
mongoose.connect("mongodb://localhost:27017/kanbas");
import UserRoutes from './users/routes.js';
import ModuleRoutes from './modules/routes.js';
import "dotenv/config";

const app = express();
app.use(cors());
app.use(express.json());
UserRoutes(app);
ModuleRoutes(app);
CourseRoutes(app);
Hello(app);
Lab5(app);
app.listen(process.env.PORT || 4000);